// <auto-generated />
using System;
using Cookbook;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cookbook.Migrations
{
    [DbContext(typeof(DbCookBookContext))]
    partial class DbCookBookContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("Cookbook.Entities.Dishes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("KindOfDietId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KindOfDishesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameOfDish")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Dishes");
                });

            modelBuilder.Entity("Cookbook.Entities.Ingredients", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameOfIngredient")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("Cookbook.Entities.KindOfDiet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("KindOfDish")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("KindOfDiet");
                });

            modelBuilder.Entity("Cookbook.Entities.KindOfdishes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("KindOfDish")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("KindOfdishes");
                });
#pragma warning restore 612, 618
        }
    }
}
